#ifndef SOCKETMUSTERPROGRAMM_LOREM_H
#define SOCKETMUSTERPROGRAMM_LOREM_H

#define LOREM_MESSAGE "\n" \
"\n" \
"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis nisl a tortor lacinia consectetur. Vestibulum accumsan bibendum mi sed ultrices. Aliquam tristique lectus orci, et aliquam lorem ullamcorper non. Nulla facilisi. Sed tempus justo at lectus commodo, at aliquam velit porta. Pellentesque gravida ex euismod lectus interdum pulvinar. Nunc ultrices bibendum feugiat. Fusce sed condimentum ex, nec efficitur velit. Nam at sem porttitor, feugiat velit sed, placerat metus. In lobortis diam et porttitor vulputate. Fusce purus purus, porta at consectetur in, viverra nec purus.\n" \
"\n" \
"Nulla hendrerit iaculis quam, eget mattis enim lacinia id. Pellentesque eget suscipit lorem. Maecenas arcu felis, viverra eu risus ut, euismod ultricies nibh. Proin suscipit odio a erat sagittis, nec finibus sem finibus. Nullam ullamcorper tellus ut diam vulputate, ut egestas nisi vulputate. Fusce vulputate, tellus vitae rhoncus pretium, turpis turpis molestie nibh, ut tincidunt sapien elit a quam. Nulla ac vestibulum elit. Quisque eget ante turpis. Aliquam nec velit ac ipsum accumsan porta.\n" \
"\n" \
"Donec vel eros at odio scelerisque porttitor ullamcorper et nibh. Integer eget commodo nunc. Donec sit amet sem feugiat, tincidunt lectus ac, ultrices lacus. Ut scelerisque ullamcorper ultricies. Phasellus nec tempor dolor. In viverra dolor eget tortor gravida, at aliquet turpis rutrum. Maecenas vitae justo risus. Aliquam orci turpis, finibus et sapien ut, volutpat vestibulum sapien. Pellentesque id justo egestas, tempus risus at, sodales risus. Ut gravida tortor id commodo cursus. Nulla vitae erat ultricies, auctor eros non, congue ante. Integer sed ornare metus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.\n" \
"\n" \
"Sed sit amet tempor arcu. Nullam quam nunc, porta vel tortor at, vestibulum interdum magna. Nam in lectus non nisi accumsan ultrices. Cras feugiat purus nec eros elementum dapibus. Ut at lectus elit. Nunc nec ornare nulla. Nulla vel malesuada neque. Vestibulum non ligula a magna egestas accumsan quis vitae quam. Aliquam id nulla non enim hendrerit sollicitudin. Vestibulum consequat vestibulum sollicitudin. Curabitur ut molestie massa. Aliquam dapibus neque placerat diam tincidunt, eget auctor nunc posuere.\n" \
"\n" \
"Mauris eget urna auctor, egestas sem sit amet, suscipit justo. Suspendisse interdum nisi id sem gravida, vitae tincidunt dui iaculis. Cras ac pulvinar elit. Donec volutpat massa est, sed porta elit semper et. Sed et mauris varius, tincidunt diam quis, pharetra lorem. Pellentesque iaculis, quam vel lacinia dictum, odio nibh lacinia eros, convallis consectetur elit neque nec arcu. Praesent nec ullamcorper ex, vel ullamcorper enim. Nulla orci massa, interdum sit amet vestibulum eu, commodo vitae mauris. Nulla venenatis mollis dapibus.\n" \
"\n" \
"Etiam auctor erat augue, ut finibus mi euismod eu. Proin fermentum nulla id magna tempor, ut pulvinar erat fringilla. Donec condimentum sem id nibh facilisis semper. Suspendisse vitae purus ac est ornare malesuada ac ut massa. Nullam nisl nunc, interdum vel aliquet in, aliquet eu quam. Nunc sodales viverra ex, tempus hendrerit eros auctor non. Donec laoreet a enim at viverra. In euismod, leo a tristique rhoncus, quam est tincidunt turpis, ac fermentum metus tortor at nunc. Proin cursus nisi nec ultricies convallis. Donec in urna iaculis, ultricies arcu id, vestibulum sapien. Nullam sed arcu eu arcu aliquam tempus sed blandit quam. Suspendisse ultricies arcu est. Donec nec commodo nunc. Maecenas nisi tortor, dignissim ac tincidunt eu, interdum in risus.\n" \
"\n" \
"In viverra, enim quis mattis ultrices, est dui mollis urna, a ornare arcu turpis ut purus. Quisque condimentum massa sed ultrices porttitor. Nulla non elementum massa. Curabitur tellus lectus, scelerisque ac porttitor quis, hendrerit id est. Nullam id imperdiet augue, tempor congue ligula. Pellentesque non erat sed nisl interdum sagittis sollicitudin sit amet ipsum. Mauris quis consequat nulla, id suscipit eros. Integer aliquam eu ipsum eu maximus. Curabitur porttitor massa eu nunc dapibus, a tempus sem efficitur.\n" \
"\n" \
"Donec aliquet neque vel maximus finibus. Sed et nisl tortor. Morbi porta ultrices ligula, ut dignissim eros accumsan et. Ut dignissim ipsum turpis, et porttitor neque malesuada ac. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed iaculis semper purus, ut maximus velit varius vitae. Integer laoreet at risus sed finibus. Cras in elit in nunc imperdiet pharetra ac vitae mi.\n" \
"\n" \
"Duis consequat laoreet odio, sit amet sodales mauris ultricies eget. Nam malesuada velit non ex malesuada blandit. Morbi dapibus interdum gravida. Quisque vitae eros at nisl semper blandit. Proin vel dolor semper, posuere sapien at, feugiat ante. Sed commodo risus non quam tincidunt, a condimentum mi congue. Nam tempor odio condimentum leo porttitor tempor. Suspendisse potenti. Integer libero urna, fringilla eget urna eu, congue consequat augue. Aliquam porttitor dui nulla, vel posuere nunc viverra sed. Fusce augue tortor, gravida ac sagittis sit amet, tincidunt eu augue. Suspendisse potenti. Praesent fermentum vestibulum ornare. Nunc elementum iaculis ultricies. Cras ipsum augue, facilisis vitae arcu eu, porttitor pharetra nibh. Pellentesque pellentesque feugiat nibh, a dapibus lectus eleifend et.\n" \
"\n" \
"Quisque iaculis sem a commodo faucibus. Proin convallis vehicula ullamcorper. Donec commodo facilisis massa id pretium. Fusce consequat lectus at ante mattis suscipit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Etiam lacinia nec turpis at molestie. Aliquam vitae est nec neque sodales laoreet in id nunc. Morbi mi diam, venenatis a malesuada eu, hendrerit quis dolor. Fusce risus nunc, feugiat ut est sed, feugiat sodales elit. Pellentesque justo nunc, suscipit a gravida vitae, mollis et tortor.\n" \
"\n" \
"Donec maximus, lorem in condimentum malesuada, velit sapien ornare neque, sed feugiat elit enim in nisi. Nam bibendum commodo sapien, bibendum rutrum turpis interdum a. Etiam rhoncus ligula vitae sollicitudin congue. Aliquam id nibh non nunc faucibus tincidunt. Nulla pulvinar augue ac neque blandit ultrices. Mauris viverra est sem, vitae scelerisque leo porta sit amet. Etiam et eros sapien. Ut in orci accumsan lorem iaculis viverra. Aliquam malesuada ullamcorper turpis, eu molestie turpis mattis vitae. Curabitur elementum tortor ligula, quis ultricies elit ullamcorper nec. Donec egestas ac est eu eleifend. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam bibendum facilisis nunc, sit amet tincidunt sem tempus nec. Phasellus ultrices posuere eros, eget porta ligula porttitor non. Sed malesuada finibus ullamcorper. Nam dolor ante, sollicitudin vitae suscipit sit amet, accumsan ut tellus.\n" \
"\n" \
"Nullam libero odio, convallis nec efficitur pulvinar, luctus sit amet ligula. Donec vitae tempor leo. Duis pharetra lacus id luctus feugiat. Fusce pharetra quam ante, laoreet feugiat magna bibendum maximus. Sed ut lorem vitae sapien bibendum convallis. Sed tincidunt mattis consequat. Etiam porttitor elementum nisl a laoreet. Donec efficitur nibh in dui sagittis, sit amet lobortis tellus interdum. Nunc eget magna sed justo ultrices aliquet at et dolor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.\n" \
"\n" \
"Fusce ac egestas urna, a faucibus nulla. Maecenas dolor turpis, tristique quis bibendum in, mattis quis metus. Phasellus at nulla consectetur, convallis sem in, molestie erat. Duis quis arcu nunc. Fusce eu orci ante. Phasellus ac suscipit tortor. Duis finibus diam metus, ut suscipit sapien lobortis vel. Pellentesque aliquet nunc a massa fermentum condimentum. Curabitur sit amet libero id turpis rutrum volutpat ut ac nibh. Maecenas vitae euismod mauris, vel tempor sapien. Vestibulum dapibus posuere cursus. Ut quis ex sit amet velit pellentesque interdum. Fusce consequat nisl non ligula pretium gravida et vulputate felis. Mauris ut suscipit neque, in ornare odio. In hac habitasse platea dictumst.\n" \
"\n" \
"Quisque nec placerat nibh, vitae finibus nibh. Ut sed nisi sit amet sem lacinia consectetur vitae in tellus. Nullam consequat nunc sit amet est porttitor, non sollicitudin felis euismod. Cras nec ligula sed nunc ultrices bibendum ut nec eros. Nunc sed elit in metus egestas aliquam vitae nec felis. Curabitur vestibulum commodo lacus, eu egestas nisi suscipit vitae. Cras leo tellus, maximus eu finibus ac, mollis non nulla. Pellentesque vitae vulputate neque. Donec nec quam eget tortor bibendum cursus.\n" \
"\n" \
"Donec eget risus et elit viverra faucibus sit amet ut dui. Etiam faucibus pulvinar velit, quis semper mauris mollis sed. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse id auctor enim. Curabitur et nisl augue. Nullam purus libero, fringilla a elit vel, scelerisque pretium mi. Morbi arcu nisl, dignissim nec orci a, lobortis ullamcorper arcu. Aenean justo nisl, eleifend sed ultricies eu, cursus ut augue. Donec condimentum dui dictum feugiat pretium. Vivamus sed neque nulla.\n" \
"\n" \
"Cras vulputate posuere placerat. Mauris tincidunt semper auctor. Integer eu metus in mauris auctor molestie. Etiam quis lacinia ipsum. Maecenas placerat venenatis nunc in finibus. In condimentum dui vel nibh hendrerit pharetra. Etiam facilisis, enim sed iaculis semper, nibh ipsum facilisis risus, vel venenatis nisi massa in ex.\n" \
"\n" \
"Aliquam erat volutpat. Donec ut sem non dolor posuere pharetra. Proin sollicitudin tellus non est feugiat, non lobortis sapien porta. Praesent quis diam tincidunt lorem imperdiet venenatis. Phasellus egestas tempor nisl id posuere. Quisque congue elit mi, in placerat ante imperdiet in. Pellentesque gravida pellentesque ante id pharetra. Curabitur dignissim libero ut porttitor volutpat. Quisque aliquet tempor nulla. Duis sem est, facilisis aliquet feugiat eu, feugiat at odio. Mauris vel purus id purus rutrum condimentum. Duis non laoreet tellus.\n" \
"\n" \
"Proin ultrices rhoncus magna, ac dapibus sem consectetur quis. Vivamus ac mauris eget mauris pretium volutpat. ";

#endif //SOCKETMUSTERPROGRAMM_LOREM_H
